/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
//veamos si sirve

import conexionBDD.Conexionn;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseMotionListener;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class Caca extends javax.swing.JInternalFrame {

    Conexionn conn;
    ArrayList establecimientos;
    String cedula_usuario;
    int anio;

    public Caca(Conexionn conn, String cedula, int anio) {
        initComponents();
        panelNegocios.setVisible(false);
        this.anio = anio;
        this.conn = conn;
        this.cedula_usuario = cedula;
        //Bloquear el movimiento del Frame
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        Component north = ui.getNorthPane();
        MouseMotionListener[] actions = (MouseMotionListener[]) north.getListeners(MouseMotionListener.class);
        for (MouseMotionListener action : actions) {
            north.removeMouseMotionListener(action);
        }

        combo_Establecimientos.removeAllItems();
        combo_Establecimientos.addItem("");
        establecimientos = conn.cargarEstablecimiento();
        for (Object est : establecimientos) {
            combo_Establecimientos.addItem(est.toString());
        }

        jComboBox1.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    // los nuevos registros son agregados al MODEL del JCombo HIJO
                    if (e.getItem().toString().equals("Gastos Personales")) {
                        panelNegocios.setVisible(false);
                        panelPersonales.setVisible(true);
                    } else {
                        panelNegocios.setVisible(true);
                        panelPersonales.setVisible(false);
                    }
                }
            }
        });

        //conn.ddl("SELECT nombre_establecimiento FROM establecimiento");
        //conn.insertar("insert into ESTABLECIMIENTO values('1234958543001','Supermaxi','Cumbaya')");
        //conn.insertar("insert into public.establecimiento values('1234958543001','Supermaxi','Cumbaya')");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        panel_establecimiento = new javax.swing.JPanel();
        combo_Establecimientos = new javax.swing.JComboBox<String>();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_ruc_est = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_direc_est = new javax.swing.JTextField();
        btnEditarEst = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_telef = new javax.swing.JTextField();
        panel_establecimiento1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        date_fecha = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_iva = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_sin_iva = new javax.swing.JTextField();
        txt_num_fac = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        panelNegocios = new javax.swing.JPanel();
        lblMercaderia = new javax.swing.JLabel();
        lblCapacitacion = new javax.swing.JLabel();
        lblServBasicos = new javax.swing.JLabel();
        lblArriendo = new javax.swing.JLabel();
        txt_Mercaderia = new javax.swing.JTextField();
        txt_arriendo = new javax.swing.JTextField();
        txt_servbasicos = new javax.swing.JTextField();
        txt_capacitacion = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        lbl_capacitacion = new javax.swing.JLabel();
        lbl_servbasicos = new javax.swing.JLabel();
        lbl_arriendo = new javax.swing.JLabel();
        lbl_mercaderia = new javax.swing.JLabel();
        lblSueldos = new javax.swing.JLabel();
        lblMovilizacion = new javax.swing.JLabel();
        lblviaticos = new javax.swing.JLabel();
        txt_viaticos = new javax.swing.JTextField();
        txt_movilizacion = new javax.swing.JTextField();
        txt_sueldos = new javax.swing.JTextField();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        lbl_viaticos = new javax.swing.JLabel();
        lbl_movilizacion = new javax.swing.JLabel();
        lbl_sueldos = new javax.swing.JLabel();
        lbl_herramientas = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        lblHerramientas = new javax.swing.JLabel();
        txt_herramientas = new javax.swing.JTextField();
        lblSuministros = new javax.swing.JLabel();
        txt_suministros = new javax.swing.JTextField();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        lbl_suministros = new javax.swing.JLabel();
        panelPersonales = new javax.swing.JPanel();
        txt_vivienda = new javax.swing.JTextField();
        txt_alimentacion = new javax.swing.JTextField();
        txt_otros = new javax.swing.JTextField();
        txt_salud = new javax.swing.JTextField();
        txt_vestimenta = new javax.swing.JTextField();
        txt_educacion = new javax.swing.JTextField();
        txt_negocio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        lbl_vivienda = new javax.swing.JLabel();
        lbl_alimentacion = new javax.swing.JLabel();
        lbl_educacion = new javax.swing.JLabel();
        lbl_otros = new javax.swing.JLabel();
        lbl_salud = new javax.swing.JLabel();
        lbl_vestimenta = new javax.swing.JLabel();
        lbl_negocio = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        btn_RegistrarFactura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1302, 226, -1, -1));

        panel_establecimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Establecimiento", 0, 0, new java.awt.Font("Open Sans Extrabold", 1, 14), java.awt.Color.black)); // NOI18N

        combo_Establecimientos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_EstablecimientosItemStateChanged(evt);
            }
        });

        jButton2.setText("Registrar Nuevo Establecimiento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(java.awt.Color.black);
        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel4.setText("Nombre/Razon Social:");

        jLabel5.setBackground(java.awt.Color.black);
        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel5.setText("RUC:");

        txt_ruc_est.setEnabled(false);

        jLabel6.setBackground(java.awt.Color.black);
        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel6.setText("Direccion:");

        txt_direc_est.setEnabled(false);

        btnEditarEst.setText("Editar Datos");
        btnEditarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEstActionPerformed(evt);
            }
        });

        jLabel10.setBackground(java.awt.Color.black);
        jLabel10.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel10.setText("Telefono:");

        txt_telef.setEnabled(false);

        javax.swing.GroupLayout panel_establecimientoLayout = new javax.swing.GroupLayout(panel_establecimiento);
        panel_establecimiento.setLayout(panel_establecimientoLayout);
        panel_establecimientoLayout.setHorizontalGroup(
            panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_establecimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_establecimientoLayout.createSequentialGroup()
                        .addGroup(panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addGap(29, 29, 29)
                        .addGroup(panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_establecimientoLayout.createSequentialGroup()
                                .addComponent(txt_ruc_est, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panel_establecimientoLayout.createSequentialGroup()
                                .addComponent(txt_telef, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_direc_est)))
                    .addGroup(panel_establecimientoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_Establecimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_establecimientoLayout.setVerticalGroup(
            panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_establecimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_Establecimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_ruc_est, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_direc_est, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_telef, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_establecimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, -1));

        panel_establecimiento1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Factura", 0, 0, new java.awt.Font("Open Sans Extrabold", 1, 14), java.awt.Color.black)); // NOI18N
        panel_establecimiento1.setLayout(null);

        jLabel8.setBackground(java.awt.Color.black);
        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel8.setText("Número de Factura:");
        panel_establecimiento1.add(jLabel8);
        jLabel8.setBounds(30, 40, 157, 17);

        jLabel9.setBackground(java.awt.Color.black);
        jLabel9.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel9.setText("Fecha de Emision:");
        panel_establecimiento1.add(jLabel9);
        jLabel9.setBounds(410, 40, 143, 17);

        jLabel15.setBackground(java.awt.Color.black);
        jLabel15.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel15.setText("Total sin iva:");
        panel_establecimiento1.add(jLabel15);
        jLabel15.setBounds(490, 280, 100, 17);

        date_fecha.setDateFormatString("yyyy-MM-dd");
        date_fecha.setPreferredSize(new java.awt.Dimension(12, 29));
        panel_establecimiento1.add(date_fecha);
        date_fecha.setBounds(560, 30, 180, 29);

        jLabel16.setBackground(java.awt.Color.black);
        jLabel16.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel16.setText("I.V.A:");
        panel_establecimiento1.add(jLabel16);
        jLabel16.setBounds(490, 320, 42, 17);

        jLabel17.setBackground(java.awt.Color.black);
        jLabel17.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel17.setText("Valor total:");
        panel_establecimiento1.add(jLabel17);
        jLabel17.setBounds(490, 360, 87, 17);

        txt_iva.setText("0.0");
        txt_iva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ivaKeyTyped(evt);
            }
        });
        panel_establecimiento1.add(txt_iva);
        txt_iva.setBounds(600, 310, 128, 33);

        txt_total.setEnabled(false);
        panel_establecimiento1.add(txt_total);
        txt_total.setBounds(600, 350, 128, 33);

        txt_sin_iva.setEnabled(false);
        panel_establecimiento1.add(txt_sin_iva);
        txt_sin_iva.setBounds(600, 270, 128, 33);
        panel_establecimiento1.add(txt_num_fac);
        txt_num_fac.setBounds(190, 30, 150, 33);

        jLabel11.setBackground(java.awt.Color.black);
        jLabel11.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel11.setText("Tipo de Factura:");
        panel_establecimiento1.add(jLabel11);
        jLabel11.setBounds(410, 80, 150, 17);

        jButton9.setText("Calcular");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton9);
        jButton9.setBounds(130, 320, 180, 60);

        jLabel12.setBackground(java.awt.Color.black);
        jLabel12.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel12.setText("Tipos de gasto:");
        panel_establecimiento1.add(jLabel12);
        jLabel12.setBounds(20, 80, 150, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gastos Personales", "Gastos de Negocio" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jComboBox1);
        jComboBox1.setBounds(560, 70, 190, 33);

        panelNegocios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMercaderia.setText("Mercaderia");
        panelNegocios.add(lblMercaderia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, -1));

        lblCapacitacion.setText("Capacitacion");
        panelNegocios.add(lblCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, -1));

        lblServBasicos.setText("Serv. Basicos ");
        panelNegocios.add(lblServBasicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, -1));

        lblArriendo.setText("Arriendo");
        panelNegocios.add(lblArriendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, -1));

        txt_Mercaderia.setDisabledTextColor(new java.awt.Color(183, 183, 183));
        txt_Mercaderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MercaderiaActionPerformed(evt);
            }
        });
        txt_Mercaderia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_MercaderiaKeyTyped(evt);
            }
        });
        panelNegocios.add(txt_Mercaderia, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 12, 91, -1));

        txt_arriendo.setDisabledTextColor(new java.awt.Color(183, 183, 183));
        txt_arriendo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_arriendoKeyTyped(evt);
            }
        });
        panelNegocios.add(txt_arriendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 52, 91, -1));

        txt_servbasicos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_servbasicosKeyTyped(evt);
            }
        });
        panelNegocios.add(txt_servbasicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 92, 91, -1));

        txt_capacitacion.setDisabledTextColor(new java.awt.Color(183, 183, 183));
        txt_capacitacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_capacitacionKeyTyped(evt);
            }
        });
        panelNegocios.add(txt_capacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 132, 91, -1));

        jButton17.setText("+");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 12, 50, -1));

        jButton18.setText("-");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 12, 50, -1));

        jButton19.setText("+");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 52, 50, -1));

        jButton20.setText("-");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 52, 50, -1));

        jButton21.setText("+");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 92, 50, -1));

        jButton22.setText("-");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 92, 50, -1));

        jButton23.setText("+");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 132, 50, -1));

        jButton24.setText("-");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 132, 50, -1));

        lbl_capacitacion.setForeground(java.awt.Color.darkGray);
        lbl_capacitacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_capacitacion.setText("0.0");
        lbl_capacitacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelNegocios.add(lbl_capacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 132, 70, 30));

        lbl_servbasicos.setForeground(java.awt.Color.darkGray);
        lbl_servbasicos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_servbasicos.setText("0.0");
        lbl_servbasicos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelNegocios.add(lbl_servbasicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 92, 70, 30));

        lbl_arriendo.setForeground(java.awt.Color.darkGray);
        lbl_arriendo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_arriendo.setText("0.0");
        lbl_arriendo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelNegocios.add(lbl_arriendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 52, 70, 30));

        lbl_mercaderia.setForeground(java.awt.Color.darkGray);
        lbl_mercaderia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_mercaderia.setText("0.0");
        lbl_mercaderia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelNegocios.add(lbl_mercaderia, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 12, 70, 30));

        lblSueldos.setText("Sueldos");
        panelNegocios.add(lblSueldos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 100, -1));

        lblMovilizacion.setText("Movilizacion");
        panelNegocios.add(lblMovilizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 100, -1));

        lblviaticos.setText("Viaticos");
        panelNegocios.add(lblviaticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 90, -1));

        txt_viaticos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_viaticosKeyTyped(evt);
            }
        });
        panelNegocios.add(txt_viaticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 92, 82, -1));

        txt_movilizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_movilizacionKeyTyped(evt);
            }
        });
        panelNegocios.add(txt_movilizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 52, 82, -1));

        txt_sueldos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sueldosKeyTyped(evt);
            }
        });
        panelNegocios.add(txt_sueldos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 82, -1));

        jButton25.setText("+");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 12, 50, -1));

        jButton26.setText("-");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 12, 50, -1));

        jButton27.setText("+");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 52, 50, -1));

        jButton28.setText("-");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 52, 50, -1));

        jButton29.setText("+");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 92, 50, -1));

        jButton30.setText("-");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 92, 50, -1));

        lbl_viaticos.setForeground(java.awt.Color.darkGray);
        lbl_viaticos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_viaticos.setText("0.0");
        lbl_viaticos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelNegocios.add(lbl_viaticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 92, 67, 30));

        lbl_movilizacion.setForeground(java.awt.Color.darkGray);
        lbl_movilizacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_movilizacion.setText("0.0");
        lbl_movilizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelNegocios.add(lbl_movilizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 52, 67, 30));

        lbl_sueldos.setForeground(java.awt.Color.darkGray);
        lbl_sueldos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_sueldos.setText("0.0");
        lbl_sueldos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelNegocios.add(lbl_sueldos, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 12, 67, 30));

        lbl_herramientas.setForeground(java.awt.Color.darkGray);
        lbl_herramientas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_herramientas.setText("0.0");
        lbl_herramientas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelNegocios.add(lbl_herramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 172, 70, 30));

        jButton31.setText("-");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 172, 50, -1));

        jButton32.setText("+");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 172, 50, -1));

        lblHerramientas.setText("Herramientas");
        panelNegocios.add(lblHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, -1));

        txt_herramientas.setDisabledTextColor(new java.awt.Color(183, 183, 183));
        txt_herramientas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_herramientasKeyTyped(evt);
            }
        });
        panelNegocios.add(txt_herramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 172, 91, -1));

        lblSuministros.setText("Suministros");
        panelNegocios.add(lblSuministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 90, -1));

        txt_suministros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_suministrosKeyTyped(evt);
            }
        });
        panelNegocios.add(txt_suministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 132, 82, -1));

        jButton33.setText("+");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 132, 50, -1));

        jButton34.setText("-");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        panelNegocios.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 132, 50, -1));

        lbl_suministros.setForeground(java.awt.Color.darkGray);
        lbl_suministros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_suministros.setText("0.0");
        lbl_suministros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelNegocios.add(lbl_suministros, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 132, 67, 30));

        panel_establecimiento1.add(panelNegocios);
        panelNegocios.setBounds(10, 100, 760, 210);

        txt_vivienda.setDisabledTextColor(new java.awt.Color(183, 183, 183));
        txt_vivienda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_viviendaKeyTyped(evt);
            }
        });

        txt_alimentacion.setDisabledTextColor(new java.awt.Color(183, 183, 183));
        txt_alimentacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_alimentacionKeyTyped(evt);
            }
        });

        txt_otros.setDisabledTextColor(new java.awt.Color(183, 183, 183));
        txt_otros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_otrosKeyTyped(evt);
            }
        });

        txt_salud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_saludKeyTyped(evt);
            }
        });

        txt_vestimenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_vestimentaKeyTyped(evt);
            }
        });

        txt_educacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_educacionKeyTyped(evt);
            }
        });

        txt_negocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_negocioKeyTyped(evt);
            }
        });

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("+");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("+");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("+");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("+");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        lbl_vivienda.setForeground(java.awt.Color.darkGray);
        lbl_vivienda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_vivienda.setText("0.0");
        lbl_vivienda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_alimentacion.setForeground(java.awt.Color.darkGray);
        lbl_alimentacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_alimentacion.setText("0.0");
        lbl_alimentacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_educacion.setForeground(java.awt.Color.darkGray);
        lbl_educacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_educacion.setText("0.0");
        lbl_educacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_otros.setForeground(java.awt.Color.darkGray);
        lbl_otros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_otros.setText("0.0");
        lbl_otros.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_salud.setForeground(java.awt.Color.darkGray);
        lbl_salud.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_salud.setText("0.0");
        lbl_salud.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_vestimenta.setForeground(java.awt.Color.darkGray);
        lbl_vestimenta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_vestimenta.setText("0.0");
        lbl_vestimenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_negocio.setForeground(java.awt.Color.darkGray);
        lbl_negocio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_negocio.setText("0.0");
        lbl_negocio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setText("Vivienda");

        jLabel20.setText("Alimentación");

        jLabel21.setText("Educación ");

        jLabel22.setText("Otros");

        jButton10.setText("-");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("-");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("-");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("-");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel23.setText("Salud");

        jLabel24.setText("Vestimenta");

        jLabel25.setText("Negocio");

        jButton14.setText("-");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("-");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("-");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPersonalesLayout = new javax.swing.GroupLayout(panelPersonales);
        panelPersonales.setLayout(panelPersonalesLayout);
        panelPersonalesLayout.setHorizontalGroup(
            panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonalesLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_vivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbl_vivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPersonalesLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(txt_salud, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbl_salud, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPersonalesLayout.createSequentialGroup()
                        .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPersonalesLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(txt_alimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbl_alimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPersonalesLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(txt_vestimenta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbl_vestimenta, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPersonalesLayout.createSequentialGroup()
                        .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPersonalesLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(txt_educacion, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbl_educacion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_negocio, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbl_negocio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPersonalesLayout.createSequentialGroup()
                        .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPersonalesLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(txt_otros, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbl_otros, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPersonalesLayout.setVerticalGroup(
            panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalesLayout.createSequentialGroup()
                .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonalesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19))
                    .addComponent(txt_vivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton10)
                    .addComponent(lbl_vivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPersonalesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel23))
                    .addComponent(txt_salud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton14)
                    .addComponent(lbl_salud, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_alimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPersonalesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20))
                    .addComponent(jButton3)
                    .addComponent(jButton11)
                    .addComponent(lbl_alimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_vestimenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPersonalesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel24))
                    .addComponent(jButton7)
                    .addComponent(jButton15)
                    .addComponent(lbl_vestimenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_educacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPersonalesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel21))
                    .addComponent(jButton6)
                    .addComponent(jButton12)
                    .addComponent(lbl_educacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPersonalesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel25))
                    .addComponent(txt_negocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)
                    .addComponent(jButton16)
                    .addComponent(lbl_negocio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panelPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonalesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel22))
                    .addComponent(txt_otros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton13)
                    .addComponent(lbl_otros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        panel_establecimiento1.add(panelPersonales);
        panelPersonales.setBounds(10, 110, 760, 160);

        getContentPane().add(panel_establecimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 780, 390));

        btn_RegistrarFactura.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btn_RegistrarFactura.setText("Registrar Factura");
        btn_RegistrarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_RegistrarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 220, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validar_vacios() {
        return ((combo_Establecimientos.getSelectedItem().equals("") || txt_num_fac.getText().equals("") || txt_total.getText().equals("") || txt_sin_iva.getText().equals("") || date_fecha.getDate() == null));

    }

    private double dar_formato(String valor) {
        return BigDecimal.valueOf(Double.parseDouble(valor)).setScale(3, RoundingMode.HALF_UP).doubleValue();
    }

    private void registrar_gastos_personales(String num_factura) {

        double totalVivienda = dar_formato(lbl_vivienda.getText()),
                totalAlimento = dar_formato(lbl_alimentacion.getText()),
                totalEducacion = dar_formato(lbl_educacion.getText()),
                totalSalud = dar_formato(lbl_salud.getText()),
                totalVestimenta = dar_formato(lbl_vestimenta.getText()),
                totalNegocio = dar_formato(lbl_negocio.getText()),
                totalOtros = dar_formato(lbl_otros.getText());

        if (totalVivienda != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Vivienda'," + totalVivienda + ")");
        }
        if (totalAlimento != 0) {    //        
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Alimentacion'," + totalAlimento + ")");
        }
        if (totalEducacion != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Educacion'," + totalEducacion + ")");
        }
        if (totalSalud != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Salud'," + totalSalud + ")");
        }
        if (totalVestimenta != 0) {//
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Vestimenta'," + totalVestimenta + ")");
        }
        if (totalNegocio != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Negocio'," + totalNegocio + ")");
        }
        if (totalOtros != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Otro'," + totalOtros + ")");
        }

        if (conn.verificar_usuario("SELECT * FROM HISTORIAL_PAGOS WHERE anio_historial=" + anio + "")) {
            conn.insertar("UPDATE HISTORIAL_PAGOS SET total_alimentacion=total_alimentacion+" + totalAlimento + "::money,"
                    + "total_salud=total_salud+" + totalSalud + "::money,"
                    + "total_vivienda=total_vivienda+" + totalVivienda + "::money,"
                    + "total_educacion=total_educacion+" + totalEducacion + "::money,"
                    + "total_vestimenta=total_vestimenta+" + totalVestimenta + "::money,"
                    + "total_negocios=total_negocios+" + totalNegocio + "::money,"
                    + "total_otros=total_otros+" + totalOtros + "::money WHERE anio_historial=" + this.anio + " AND id_cliente='" + this.cedula_usuario + "'");

        } else {
            conn.insertar("INSERT INTO HISTORIAL_PAGOS VALUES (" + anio + ",'" + cedula_usuario + "'," + totalAlimento + "," + totalSalud + "," + totalVivienda + "," + totalEducacion + "," + totalVestimenta + "," + totalNegocio + "," + totalOtros + ")");
        }

        JOptionPane.showMessageDialog(null, "Ingreso Exitoso");
    }

    private void registrar_gastos_negocio(String num_factura) {

        double totalMercaderia = dar_formato(lbl_mercaderia.getText()),
                totalArriendo = dar_formato(lbl_arriendo.getText()),
                totalServBasicos = dar_formato(lbl_servbasicos.getText()),
                totalCapacitacion = dar_formato(lbl_capacitacion.getText()),
                totalHerramientas = dar_formato(lbl_herramientas.getText()),
                totalSueldos = dar_formato(lbl_sueldos.getText()),
                totalMovilizacion = dar_formato(lbl_movilizacion.getText()),
                totalViaticos = dar_formato(lbl_viaticos.getText()),
                totalSuministros = dar_formato(lbl_suministros.getText());

        if (totalMercaderia != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Mercaderia'," + totalMercaderia + ")");
        }
        if (totalArriendo!= 0) {    //        
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Arriendo'," + totalArriendo + ")");
        }
        if (totalServBasicos != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Servicios Basicos'," + totalServBasicos + ")");
        }
        if (totalCapacitacion != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Capacitacion'," + totalCapacitacion + ")");
        }
        if (totalHerramientas != 0) {//
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Herramientas'," + totalHerramientas + ")");
        }
        if (totalSueldos != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Sueldos'," + totalSueldos + ")");
        }
        if (totalMovilizacion != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Movilizacion'," + totalMovilizacion + ")");
        }
        
        if (totalViaticos != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Viaticos'," + totalViaticos + ")");
        }
        if (totalSuministros != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Suministros'," + totalSuministros + ")");
        }

       /* if (conn.verificar_usuario("SELECT * FROM HISTORIAL_PAGOS WHERE anio_historial=" + anio + "")) {
            conn.insertar("UPDATE HISTORIAL_PAGOS SET total_alimentacion=total_alimentacion+" + totalAlimento + "::money,"
                    + "total_salud=total_salud+" + totalSalud + "::money,"
                    + "total_vivienda=total_vivienda+" + totalVivienda + "::money,"
                    + "total_educacion=total_educacion+" + totalEducacion + "::money,"
                    + "total_vestimenta=total_vestimenta+" + totalVestimenta + "::money,"
                    + "total_negocios=total_negocios+" + totalNegocio + "::money,"
                    + "total_otros=total_otros+" + totalOtros + "::money WHERE anio_historial=" + this.anio + " AND id_cliente='" + this.cedula_usuario + "'");

        } else {
            conn.insertar("INSERT INTO HISTORIAL_PAGOS VALUES (" + anio + ",'" + cedula_usuario + "'," + totalAlimento + "," + totalSalud + "," + totalVivienda + "," + totalEducacion + "," + totalVestimenta + "," + totalNegocio + "," + totalOtros + ")");
        }

        JOptionPane.showMessageDialog(null, "Ingreso Exitoso");*/
    }
    
    private void borrar_campos() {
        combo_Establecimientos.setSelectedIndex(0);
        txt_num_fac.setText(null);
        date_fecha.setDate(null);
        JLabel labels[] = {lbl_vestimenta, lbl_vivienda, lbl_educacion, lbl_alimentacion, lbl_negocio, lbl_otros, lbl_salud,lbl_arriendo,
        lbl_capacitacion,lbl_herramientas,lbl_mercaderia,lbl_movilizacion,lbl_servbasicos,lbl_sueldos,lbl_suministros,lbl_viaticos};
        for (int i = 0; i < 16; i++) {
            labels[i].setText("0.0");
        }
        txt_sin_iva.setText(null);
        txt_iva.setText("0.0");
        txt_total.setText(null);

    }

    private void validar_iva() {
        double total_aux = dar_formato(txt_iva.getText()) + dar_formato(txt_sin_iva.getText()),
                total_con_iva = dar_formato(txt_total.getText());
        if (total_con_iva != total_aux) {
            txt_total.setText(total_aux + "");
        }
    }

    private void btn_RegistrarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarFacturaActionPerformed

        if (!validar_vacios()) {
            try {
                String num_factura = txt_num_fac.getText();
                if (!conn.verificar_usuario("SELECT * FROM FACTURA WHERE id_factura='" + num_factura + "'")) {
                    String fecha = new SimpleDateFormat("yyyy-MM-dd").format(date_fecha.getDate());
                    validar_iva();
                    double iva = dar_formato(txt_iva.getText()),
                            total_sin_iva = dar_formato(txt_sin_iva.getText()),
                            total_con_iva = dar_formato(txt_total.getText());

                    conn.insertar("INSERT INTO FACTURA (id_factura, id_cliente, id_establecimiento, fecha_emision, total_sin_iva, iva, total_con_iva)"
                            + "VALUES('" + num_factura + "','" + cedula_usuario + "','" + txt_ruc_est.getText() + "','" + fecha + "'," + total_sin_iva + "," + iva + "," + total_con_iva + ")");
                    //Registro de todos los tipos de gastos
                    registrar_gastos_personales(num_factura);
                    borrar_campos();
                } else {
                    JOptionPane.showMessageDialog(null, "El numero de factura ya existe en la base de datos");
                }
            } catch (Exception e) {
                System.err.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, llenar todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_RegistrarFacturaActionPerformed

    private void btnEditarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEstActionPerformed
        String[] datos = new String[4];
        datos[0] = (String) combo_Establecimientos.getSelectedItem();
        datos[1] = txt_direc_est.getText();
        datos[2] = txt_telef.getText();
        datos[3] = txt_ruc_est.getText();

        new V_Establecimiento("Editar", datos, conn).setVisible(true);
    }//GEN-LAST:event_btnEditarEstActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new V_Establecimiento("Registrar", conn).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void combo_EstablecimientosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_EstablecimientosItemStateChanged
        ArrayList auxDatosEst;
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (combo_Establecimientos.getSelectedIndex() != 0) {
                auxDatosEst = conn.cambiarDatosEstablecimiento(combo_Establecimientos.getSelectedItem().toString());
                txt_ruc_est.setText(auxDatosEst.get(0).toString());
                txt_direc_est.setText(auxDatosEst.get(1).toString());
            } else {
                txt_ruc_est.setText("");
                txt_direc_est.setText("");
            }
        }
    }//GEN-LAST:event_combo_EstablecimientosItemStateChanged

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        restar(lbl_negocio, txt_negocio);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        restar(lbl_vestimenta, txt_vestimenta);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        restar(lbl_salud, txt_salud);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        restar(lbl_otros, txt_otros);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        restar(lbl_educacion, txt_educacion);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        restar(lbl_alimentacion, txt_alimentacion);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        restar(lbl_vivienda, txt_vivienda);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void agregar_todo() {
        JTextField campos[] = {txt_vestimenta, txt_vivienda, txt_educacion, txt_alimentacion, txt_negocio, txt_otros, txt_salud};
        JLabel labels[] = {lbl_vestimenta, lbl_vivienda, lbl_educacion, lbl_alimentacion, lbl_negocio, lbl_otros, lbl_salud};
        String valor;
        for (int i = 0; i < 7; i++) {
            valor = campos[i].getText();
            if (!valor.equals("")) {
                sumar(labels[i], campos[i]);
            }
        }
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        agregar_todo();
        double totalNoIva = 0;
        if (jComboBox1.getSelectedItem().toString().equals("Gastos Personales")) {
            totalNoIva = Double.parseDouble(lbl_vivienda.getText()) + Double.parseDouble(lbl_alimentacion.getText())
                    + Double.parseDouble(lbl_educacion.getText()) + Double.parseDouble(lbl_otros.getText())
                    + Double.parseDouble(lbl_salud.getText()) + Double.parseDouble(lbl_vestimenta.getText()) + Double.parseDouble(lbl_negocio.getText());
        } else {
            totalNoIva = Double.parseDouble(lbl_mercaderia.getText()) + Double.parseDouble(lbl_arriendo.getText())
                    + Double.parseDouble(lbl_servbasicos.getText()) + Double.parseDouble(lbl_capacitacion.getText())
                    + Double.parseDouble(lbl_herramientas.getText()) + Double.parseDouble(lbl_sueldos.getText()) + Double.parseDouble(lbl_movilizacion.getText())
                    + Double.parseDouble(lbl_movilizacion.getText()) + Double.parseDouble(lbl_viaticos.getText()) + Double.parseDouble(lbl_suministros.getText());
        }
        txt_sin_iva.setText(totalNoIva + "");
        double totalIVA = totalNoIva + Double.parseDouble(txt_iva.getText());
        txt_total.setText(totalIVA + "");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        sumar(lbl_negocio, txt_negocio);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        sumar(lbl_vestimenta, txt_vestimenta);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        sumar(lbl_educacion, txt_educacion);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        sumar(lbl_salud, txt_salud);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        sumar(lbl_otros, txt_otros);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        sumar(lbl_alimentacion, txt_alimentacion);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sumar(JLabel lbl, JTextField txt) {
        String valor = txt.getText();
        if (!valor.equals("")) {
            lbl.setText(Double.parseDouble(lbl.getText()) + Double.parseDouble(valor) + "");
            txt.setText("");
        }

    }

    private void restar(JLabel lbl, JTextField txt) {
        String valor = txt.getText();
        if (!valor.equals("")) {
            double res = Double.parseDouble(lbl.getText()) - Double.parseDouble(valor);
            if (res < 0) {
                lbl.setText("0.0");
            } else {
                lbl.setText(res + "");
            }
            txt.setText("");
        }

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        sumar(lbl_vivienda, txt_vivienda);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void filtrar(java.awt.event.KeyEvent evt, JTextField txt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && !(c == '.')) {
            getToolkit();
            evt.consume();
        }
        if ((c == '.') && (txt_vivienda.getText().contains("."))) {
            getToolkit();
            evt.consume();
        }
    }

    private void txt_negocioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_negocioKeyTyped
        filtrar(evt, txt_negocio);
    }//GEN-LAST:event_txt_negocioKeyTyped

    private void txt_educacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_educacionKeyTyped
        filtrar(evt, txt_educacion);
    }//GEN-LAST:event_txt_educacionKeyTyped

    private void txt_vestimentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_vestimentaKeyTyped
        filtrar(evt, txt_vestimenta);
    }//GEN-LAST:event_txt_vestimentaKeyTyped

    private void txt_saludKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_saludKeyTyped
        filtrar(evt, txt_salud);
    }//GEN-LAST:event_txt_saludKeyTyped

    private void txt_otrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_otrosKeyTyped
        filtrar(evt, txt_otros);
    }//GEN-LAST:event_txt_otrosKeyTyped

    private void txt_alimentacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_alimentacionKeyTyped
        filtrar(evt, txt_alimentacion);
    }//GEN-LAST:event_txt_alimentacionKeyTyped

    private void txt_viviendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_viviendaKeyTyped
        filtrar(evt, txt_vivienda);
    }//GEN-LAST:event_txt_viviendaKeyTyped

    private void txt_ivaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ivaKeyTyped
        filtrar(evt, txt_iva);
    }//GEN-LAST:event_txt_ivaKeyTyped

    private void txt_MercaderiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MercaderiaKeyTyped
        filtrar(evt, txt_Mercaderia);         // TODO add your handling code here:
    }//GEN-LAST:event_txt_MercaderiaKeyTyped

    private void txt_arriendoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_arriendoKeyTyped
        filtrar(evt, txt_arriendo);         // TODO add your handling code here:
    }//GEN-LAST:event_txt_arriendoKeyTyped

    private void txt_servbasicosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_servbasicosKeyTyped
        filtrar(evt, txt_servbasicos);
    }//GEN-LAST:event_txt_servbasicosKeyTyped

    private void txt_capacitacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_capacitacionKeyTyped
        filtrar(evt, txt_capacitacion);
    }//GEN-LAST:event_txt_capacitacionKeyTyped

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        sumar(lbl_mercaderia, txt_Mercaderia);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        restar(lbl_mercaderia, txt_Mercaderia);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        sumar(lbl_arriendo, txt_arriendo);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        restar(lbl_arriendo, txt_arriendo);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        sumar(lbl_servbasicos, txt_servbasicos);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        restar(lbl_servbasicos, txt_servbasicos);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        sumar(lbl_capacitacion, txt_capacitacion);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        restar(lbl_capacitacion, txt_capacitacion);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void txt_viaticosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_viaticosKeyTyped
        filtrar(evt, txt_viaticos);
    }//GEN-LAST:event_txt_viaticosKeyTyped

    private void txt_movilizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_movilizacionKeyTyped
        filtrar(evt, txt_movilizacion);
    }//GEN-LAST:event_txt_movilizacionKeyTyped

    private void txt_sueldosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sueldosKeyTyped
        filtrar(evt, txt_sueldos);
    }//GEN-LAST:event_txt_sueldosKeyTyped

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        sumar(lbl_sueldos, txt_sueldos);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        restar(lbl_sueldos, txt_sueldos);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        sumar(lbl_movilizacion, txt_movilizacion);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        restar(lbl_movilizacion, txt_movilizacion);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        sumar(lbl_viaticos, txt_viaticos);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        restar(lbl_viaticos, txt_viaticos);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        restar(lbl_herramientas, txt_herramientas);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        sumar(lbl_herramientas, txt_herramientas);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed

    private void txt_herramientasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_herramientasKeyTyped
        filtrar(evt, txt_herramientas);
    }//GEN-LAST:event_txt_herramientasKeyTyped

    private void txt_suministrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_suministrosKeyTyped
        filtrar(evt, txt_suministros);
    }//GEN-LAST:event_txt_suministrosKeyTyped

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        sumar(lbl_suministros, txt_suministros);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        restar(lbl_suministros, txt_suministros);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton34ActionPerformed

    private void txt_MercaderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MercaderiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MercaderiaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturaManualNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturaManualNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturaManualNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturaManualNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                // new FacturaManualNew().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarEst;
    private javax.swing.JButton btn_RegistrarFactura;
    public static javax.swing.JComboBox<String> combo_Establecimientos;
    private com.toedter.calendar.JDateChooser date_fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblArriendo;
    private javax.swing.JLabel lblCapacitacion;
    private javax.swing.JLabel lblHerramientas;
    private javax.swing.JLabel lblMercaderia;
    private javax.swing.JLabel lblMovilizacion;
    private javax.swing.JLabel lblServBasicos;
    private javax.swing.JLabel lblSueldos;
    private javax.swing.JLabel lblSuministros;
    private javax.swing.JLabel lbl_alimentacion;
    private javax.swing.JLabel lbl_arriendo;
    private javax.swing.JLabel lbl_capacitacion;
    private javax.swing.JLabel lbl_educacion;
    private javax.swing.JLabel lbl_herramientas;
    private javax.swing.JLabel lbl_mercaderia;
    private javax.swing.JLabel lbl_movilizacion;
    private javax.swing.JLabel lbl_negocio;
    private javax.swing.JLabel lbl_otros;
    private javax.swing.JLabel lbl_salud;
    private javax.swing.JLabel lbl_servbasicos;
    private javax.swing.JLabel lbl_sueldos;
    private javax.swing.JLabel lbl_suministros;
    private javax.swing.JLabel lbl_vestimenta;
    private javax.swing.JLabel lbl_viaticos;
    private javax.swing.JLabel lbl_vivienda;
    private javax.swing.JLabel lblviaticos;
    private javax.swing.JPanel panelNegocios;
    private javax.swing.JPanel panelPersonales;
    private javax.swing.JPanel panel_establecimiento;
    private javax.swing.JPanel panel_establecimiento1;
    private javax.swing.JTextField txt_Mercaderia;
    private javax.swing.JTextField txt_alimentacion;
    private javax.swing.JTextField txt_arriendo;
    private javax.swing.JTextField txt_capacitacion;
    private javax.swing.JTextField txt_direc_est;
    private javax.swing.JTextField txt_educacion;
    private javax.swing.JTextField txt_herramientas;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_movilizacion;
    private javax.swing.JTextField txt_negocio;
    private javax.swing.JTextField txt_num_fac;
    private javax.swing.JTextField txt_otros;
    private javax.swing.JTextField txt_ruc_est;
    private javax.swing.JTextField txt_salud;
    private javax.swing.JTextField txt_servbasicos;
    private javax.swing.JTextField txt_sin_iva;
    private javax.swing.JTextField txt_sueldos;
    private javax.swing.JTextField txt_suministros;
    private javax.swing.JTextField txt_telef;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_vestimenta;
    private javax.swing.JTextField txt_viaticos;
    private javax.swing.JTextField txt_vivienda;
    // End of variables declaration//GEN-END:variables
}
