/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
//veamos si sirve

import conexionBDD.Conexionn;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.MouseMotionListener;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class FacturaManualNegocio extends javax.swing.JInternalFrame {

    Conexionn conn;
    ArrayList establecimientos;
    String cedula_usuario;
    int anio;

    public FacturaManualNegocio(Conexionn conn, String cedula, int anio) {
        initComponents();
        this.anio = anio;
        this.conn = conn;
        this.cedula_usuario = cedula;
        //Bloquear el movimiento del Frame
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        Component north = ui.getNorthPane();
        MouseMotionListener[] actions
                = (MouseMotionListener[]) north.getListeners(MouseMotionListener.class);
        for (MouseMotionListener action : actions) {
            north.removeMouseMotionListener(action);
        }

        combo_Establecimientos.removeAllItems();
        combo_Establecimientos.addItem("");
        establecimientos = conn.cargarEstablecimiento();
        for (Object est : establecimientos) {
            combo_Establecimientos.addItem(est.toString());
        }

        //fecha minima
        date_fecha.setMinSelectableDate(new Date(anio - 1900, 0, 1));
        //fecha maxima
        Date n = new Date();

        if ((n.getYear() + 1900) == anio) {
            date_fecha.setMaxSelectableDate(n);
        } else {
            date_fecha.setMaxSelectableDate(new Date(anio - 1900, 11, 31));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        panel_establecimiento = new javax.swing.JPanel();
        combo_Establecimientos = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_ruc_est = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_direc_est = new javax.swing.JTextField();
        btnEditarEst = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_telef = new javax.swing.JTextField();
        panel_establecimiento1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        date_fecha = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_iva = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_sin_iva = new javax.swing.JTextField();
        txt_num_fac = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_mercaderia = new javax.swing.JTextField();
        txt_arriendo = new javax.swing.JTextField();
        txt_capacitacion = new javax.swing.JTextField();
        txt_sueldos = new javax.swing.JTextField();
        txt_movilizacion = new javax.swing.JTextField();
        txt_servbasicos = new javax.swing.JTextField();
        txt_viaticos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        lbl_mercaderia = new javax.swing.JLabel();
        lbl_arriendo = new javax.swing.JLabel();
        lbl_servbasicos = new javax.swing.JLabel();
        lbl_capacitacion = new javax.swing.JLabel();
        lbl_sueldos = new javax.swing.JLabel();
        lbl_movilizacion = new javax.swing.JLabel();
        lbl_viaticos = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        txt_suministros = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        lbl_suministros = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        txt_herramientas = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        lbl_herramientas = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        btn_RegistrarFactura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1302, 226, -1, -1));

        panel_establecimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Establecimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Open Sans Extrabold", 1, 14), java.awt.Color.black)); // NOI18N

        combo_Establecimientos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_EstablecimientosItemStateChanged(evt);
            }
        });

        jButton2.setText("Registrar Nuevo Establecimiento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(java.awt.Color.black);
        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel4.setText("Nombre/Razon Social:");

        jLabel5.setBackground(java.awt.Color.black);
        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel5.setText("RUC:");

        txt_ruc_est.setEnabled(false);

        jLabel6.setBackground(java.awt.Color.black);
        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel6.setText("Direccion:");

        txt_direc_est.setEnabled(false);

        btnEditarEst.setText("Editar Datos");
        btnEditarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEstActionPerformed(evt);
            }
        });

        jLabel10.setBackground(java.awt.Color.black);
        jLabel10.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel10.setText("Telefono:");

        txt_telef.setEnabled(false);

        javax.swing.GroupLayout panel_establecimientoLayout = new javax.swing.GroupLayout(panel_establecimiento);
        panel_establecimiento.setLayout(panel_establecimientoLayout);
        panel_establecimientoLayout.setHorizontalGroup(
            panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_establecimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_establecimientoLayout.createSequentialGroup()
                        .addGroup(panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addGap(29, 29, 29)
                        .addGroup(panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_establecimientoLayout.createSequentialGroup()
                                .addComponent(txt_ruc_est, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panel_establecimientoLayout.createSequentialGroup()
                                .addComponent(txt_telef, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_direc_est)))
                    .addGroup(panel_establecimientoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_Establecimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_establecimientoLayout.setVerticalGroup(
            panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_establecimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_Establecimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_ruc_est, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_direc_est, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_establecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_telef, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_establecimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, -1));

        panel_establecimiento1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Open Sans Extrabold", 1, 14), java.awt.Color.black)); // NOI18N
        panel_establecimiento1.setLayout(null);

        jLabel8.setBackground(java.awt.Color.black);
        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel8.setText("Número de Factura:");
        panel_establecimiento1.add(jLabel8);
        jLabel8.setBounds(30, 30, 157, 17);

        jLabel9.setBackground(java.awt.Color.black);
        jLabel9.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel9.setText("Fecha de Emision:");
        panel_establecimiento1.add(jLabel9);
        jLabel9.setBounds(410, 30, 143, 17);

        jLabel15.setBackground(java.awt.Color.black);
        jLabel15.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel15.setText("Total sin iva:");
        panel_establecimiento1.add(jLabel15);
        jLabel15.setBounds(500, 270, 100, 17);

        date_fecha.setDateFormatString("yyyy-MM-dd");
        date_fecha.setPreferredSize(new java.awt.Dimension(12, 29));
        panel_establecimiento1.add(date_fecha);
        date_fecha.setBounds(560, 20, 180, 29);

        jLabel16.setBackground(java.awt.Color.black);
        jLabel16.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel16.setText("I.V.A:");
        panel_establecimiento1.add(jLabel16);
        jLabel16.setBounds(500, 310, 42, 17);

        jLabel17.setBackground(java.awt.Color.black);
        jLabel17.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel17.setText("Valor total:");
        panel_establecimiento1.add(jLabel17);
        jLabel17.setBounds(500, 350, 87, 17);

        txt_iva.setText("0.0");
        txt_iva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ivaKeyTyped(evt);
            }
        });
        panel_establecimiento1.add(txt_iva);
        txt_iva.setBounds(610, 300, 128, 29);

        txt_total.setEnabled(false);
        panel_establecimiento1.add(txt_total);
        txt_total.setBounds(610, 340, 128, 29);

        txt_sin_iva.setEnabled(false);
        panel_establecimiento1.add(txt_sin_iva);
        txt_sin_iva.setBounds(610, 260, 128, 29);

        txt_num_fac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_num_facKeyTyped(evt);
            }
        });
        panel_establecimiento1.add(txt_num_fac);
        txt_num_fac.setBounds(190, 20, 150, 29);

        jLabel11.setBackground(java.awt.Color.black);
        jLabel11.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel11.setText("Tipos de gasto:");
        panel_establecimiento1.add(jLabel11);
        jLabel11.setBounds(10, 60, 150, 17);

        txt_mercaderia.setDisabledTextColor(new java.awt.Color(183, 183, 183));
        txt_mercaderia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_mercaderiaKeyTyped(evt);
            }
        });
        panel_establecimiento1.add(txt_mercaderia);
        txt_mercaderia.setBounds(110, 80, 91, 29);

        txt_arriendo.setDisabledTextColor(new java.awt.Color(183, 183, 183));
        txt_arriendo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_arriendoKeyTyped(evt);
            }
        });
        panel_establecimiento1.add(txt_arriendo);
        txt_arriendo.setBounds(110, 120, 91, 29);

        txt_capacitacion.setDisabledTextColor(new java.awt.Color(183, 183, 183));
        txt_capacitacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_capacitacionKeyTyped(evt);
            }
        });
        panel_establecimiento1.add(txt_capacitacion);
        txt_capacitacion.setBounds(110, 200, 91, 29);

        txt_sueldos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sueldosKeyTyped(evt);
            }
        });
        panel_establecimiento1.add(txt_sueldos);
        txt_sueldos.setBounds(490, 80, 82, 29);

        txt_movilizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_movilizacionKeyTyped(evt);
            }
        });
        panel_establecimiento1.add(txt_movilizacion);
        txt_movilizacion.setBounds(490, 120, 82, 29);

        txt_servbasicos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_servbasicosKeyTyped(evt);
            }
        });
        panel_establecimiento1.add(txt_servbasicos);
        txt_servbasicos.setBounds(110, 160, 91, 29);

        txt_viaticos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_viaticosKeyTyped(evt);
            }
        });
        panel_establecimiento1.add(txt_viaticos);
        txt_viaticos.setBounds(490, 160, 82, 29);

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton1);
        jButton1.setBounds(210, 80, 50, 29);

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton3);
        jButton3.setBounds(210, 120, 50, 29);

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton4);
        jButton4.setBounds(210, 200, 50, 29);

        jButton5.setText("+");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton5);
        jButton5.setBounds(580, 80, 50, 29);

        jButton6.setText("+");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton6);
        jButton6.setBounds(210, 160, 50, 29);

        jButton7.setText("+");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton7);
        jButton7.setBounds(580, 120, 50, 29);

        jButton8.setText("+");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton8);
        jButton8.setBounds(580, 160, 50, 29);

        lbl_mercaderia.setForeground(java.awt.Color.darkGray);
        lbl_mercaderia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_mercaderia.setText("0.0");
        lbl_mercaderia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_establecimiento1.add(lbl_mercaderia);
        lbl_mercaderia.setBounds(320, 80, 70, 30);

        lbl_arriendo.setForeground(java.awt.Color.darkGray);
        lbl_arriendo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_arriendo.setText("0.0");
        lbl_arriendo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_establecimiento1.add(lbl_arriendo);
        lbl_arriendo.setBounds(320, 120, 70, 30);

        lbl_servbasicos.setForeground(java.awt.Color.darkGray);
        lbl_servbasicos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_servbasicos.setText("0.0");
        lbl_servbasicos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_establecimiento1.add(lbl_servbasicos);
        lbl_servbasicos.setBounds(320, 160, 70, 30);

        lbl_capacitacion.setForeground(java.awt.Color.darkGray);
        lbl_capacitacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_capacitacion.setText("0.0");
        lbl_capacitacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_establecimiento1.add(lbl_capacitacion);
        lbl_capacitacion.setBounds(320, 200, 70, 30);

        lbl_sueldos.setForeground(java.awt.Color.darkGray);
        lbl_sueldos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_sueldos.setText("0.0");
        lbl_sueldos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_establecimiento1.add(lbl_sueldos);
        lbl_sueldos.setBounds(690, 80, 67, 30);

        lbl_movilizacion.setForeground(java.awt.Color.darkGray);
        lbl_movilizacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_movilizacion.setText("0.0");
        lbl_movilizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_establecimiento1.add(lbl_movilizacion);
        lbl_movilizacion.setBounds(690, 120, 67, 30);

        lbl_viaticos.setForeground(java.awt.Color.darkGray);
        lbl_viaticos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_viaticos.setText("0.0");
        lbl_viaticos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_establecimiento1.add(lbl_viaticos);
        lbl_viaticos.setBounds(690, 160, 67, 30);

        jButton9.setText("Calcular");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton9);
        jButton9.setBounds(80, 300, 180, 60);

        jLabel19.setText("Mercadería");
        panel_establecimiento1.add(jLabel19);
        jLabel19.setBounds(10, 90, 100, 17);

        jLabel20.setText("Arriendo");
        panel_establecimiento1.add(jLabel20);
        jLabel20.setBounds(10, 130, 140, 17);

        jLabel21.setText("Serv. Básicos");
        panel_establecimiento1.add(jLabel21);
        jLabel21.setBounds(10, 170, 130, 17);

        jLabel22.setText("Capacitación");
        panel_establecimiento1.add(jLabel22);
        jLabel22.setBounds(10, 210, 120, 17);

        jButton10.setText("-");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton10);
        jButton10.setBounds(260, 80, 50, 29);

        jButton11.setText("-");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton11);
        jButton11.setBounds(260, 120, 50, 29);

        jButton12.setText("-");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton12);
        jButton12.setBounds(260, 160, 50, 29);

        jButton13.setText("-");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton13);
        jButton13.setBounds(260, 200, 50, 29);

        jLabel23.setText("Sueldos");
        panel_establecimiento1.add(jLabel23);
        jLabel23.setBounds(400, 90, 100, 17);

        jLabel24.setText("Movilización");
        panel_establecimiento1.add(jLabel24);
        jLabel24.setBounds(400, 130, 100, 17);

        jLabel25.setText("Viáticos");
        panel_establecimiento1.add(jLabel25);
        jLabel25.setBounds(400, 170, 90, 17);

        jButton14.setText("-");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton14);
        jButton14.setBounds(630, 80, 50, 29);

        jButton15.setText("-");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton15);
        jButton15.setBounds(630, 120, 50, 29);

        jButton16.setText("-");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton16);
        jButton16.setBounds(630, 160, 50, 29);

        txt_suministros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_suministrosKeyTyped(evt);
            }
        });
        panel_establecimiento1.add(txt_suministros);
        txt_suministros.setBounds(490, 200, 82, 29);

        jButton17.setText("+");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton17);
        jButton17.setBounds(580, 200, 50, 29);

        lbl_suministros.setForeground(java.awt.Color.darkGray);
        lbl_suministros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_suministros.setText("0.0");
        lbl_suministros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_establecimiento1.add(lbl_suministros);
        lbl_suministros.setBounds(690, 200, 67, 30);

        jLabel26.setText("Suministros");
        panel_establecimiento1.add(jLabel26);
        jLabel26.setBounds(400, 210, 90, 17);

        jButton18.setText("-");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton18);
        jButton18.setBounds(630, 200, 50, 29);

        txt_herramientas.setDisabledTextColor(new java.awt.Color(183, 183, 183));
        txt_herramientas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_herramientasKeyTyped(evt);
            }
        });
        panel_establecimiento1.add(txt_herramientas);
        txt_herramientas.setBounds(110, 240, 91, 29);

        jButton19.setText("+");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton19);
        jButton19.setBounds(210, 240, 50, 29);

        lbl_herramientas.setForeground(java.awt.Color.darkGray);
        lbl_herramientas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_herramientas.setText("0.0");
        lbl_herramientas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_establecimiento1.add(lbl_herramientas);
        lbl_herramientas.setBounds(320, 240, 70, 30);

        jLabel27.setText("Herramientas");
        panel_establecimiento1.add(jLabel27);
        jLabel27.setBounds(10, 250, 120, 17);

        jButton20.setText("-");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        panel_establecimiento1.add(jButton20);
        jButton20.setBounds(260, 240, 50, 29);

        getContentPane().add(panel_establecimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 770, 380));

        btn_RegistrarFactura.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btn_RegistrarFactura.setText("Registrar Factura");
        btn_RegistrarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_RegistrarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 610, 220, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validar_vacios() {
        return ((combo_Establecimientos.getSelectedItem().equals("") || txt_num_fac.getText().equals("") || date_fecha.getDate() == null));

    }

    private double dar_formato(String valor) {
        return BigDecimal.valueOf(Double.parseDouble(valor)).setScale(3, RoundingMode.HALF_UP).doubleValue();
    }

    private void registrar_gastos(String num_factura) {

        double totalMercaderia = dar_formato(lbl_mercaderia.getText()),
                totalArriendo = dar_formato(lbl_arriendo.getText()),
                totalServicios = dar_formato(lbl_servbasicos.getText()),
                totalSueldos = dar_formato(lbl_sueldos.getText()),
                totalMovilizacion = dar_formato(lbl_movilizacion.getText()),
                totalViaticos = dar_formato(lbl_viaticos.getText()),
                totalCapacitacion = dar_formato(lbl_capacitacion.getText()),
                totalSuministros = dar_formato(lbl_suministros.getText()),
                totalHerramientas = dar_formato(lbl_herramientas.getText());

        if (totalMercaderia != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Mercadería'," + totalMercaderia + ")");
        }
        if (totalArriendo != 0) {    //        
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Arriendo'," + totalArriendo + ")");
        }
        if (totalServicios != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Servicios Basicos'," + totalServicios + ")");
        }
        if (totalSueldos != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Sueldos'," + totalSueldos + ")");
        }
        if (totalMovilizacion != 0) {//
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Movilizacion'," + totalMovilizacion + ")");
        }
        if (totalViaticos != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Viaticos'," + totalViaticos + ")");
        }
        if (totalCapacitacion != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Capacitacion'," + totalCapacitacion + ")");
        }

        if (totalSuministros != 0) {
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Suministros'," + totalSuministros + ")");
        }
        if (totalHerramientas != 0) {    //        
            conn.insertar("INSERT INTO tipo_gasto (id_factura,tipo, total)"
                    + "VALUES('" + num_factura + "','Herramientas'," + totalHerramientas + ")");
        }

        if (conn.verificar_usuario("SELECT * FROM HISTORIAL_PAGOS_NEGOCIOS WHERE anio_historial_n=" + anio + " AND id_cliente='" + cedula_usuario + "'")) {
            conn.insertar("UPDATE HISTORIAL_PAGOS_NEGOCIOS SET total_mercaderia=total_mercaderia+" + totalMercaderia + "::money,"
                    + "total_arriendo=total_arriendo+" + totalArriendo + "::money,"
                    + "total_servicios=total_servicios+" + totalServicios + "::money,"
                    + "total_sueldos=total_sueldos+" + totalSueldos + "::money,"
                    + "total_movilizacion=total_movilizacion+" + totalMovilizacion + "::money,"
                    + "total_viaticos=total_viaticos+" + totalViaticos + "::money,"
                    + "total_capacitacion=total_capacitacion+" + totalCapacitacion + "::money,"
                    + "total_suministros=total_suministros+" + totalSuministros + "::money,"
                    + "total_herramientas=total_herramientas+" + totalHerramientas + "::money WHERE anio_historial_n=" + this.anio + " AND id_cliente='" + this.cedula_usuario + "'");

        } else {
            conn.insertar("INSERT INTO HISTORIAL_PAGOS_NEGOCIOS VALUES (" + anio + ",'" + cedula_usuario + "'," + totalMercaderia + ","
                    + totalArriendo + "," + totalServicios + "," + totalSueldos + "," + totalMovilizacion + "," + totalViaticos + ","
                    + totalCapacitacion + "," + totalSuministros + "," + totalHerramientas + ")");
        }

        JOptionPane.showMessageDialog(null, "Ingreso Exitoso");
    }

    private void borrar_campos() {
        combo_Establecimientos.setSelectedIndex(0);
        txt_num_fac.setText(null);
        date_fecha.setDate(null);
        JLabel labels[] = {lbl_movilizacion, lbl_mercaderia, lbl_servbasicos, lbl_arriendo, lbl_viaticos, lbl_capacitacion, lbl_sueldos, lbl_herramientas, lbl_suministros};
        for (int i = 0; i < 9; i++) {
            labels[i].setText("0.0");
        }
        txt_sin_iva.setText(null);
        txt_iva.setText("0.0");
        txt_total.setText(null);

    }

    private void btn_RegistrarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarFacturaActionPerformed
        jButton9ActionPerformed(evt);
        if (!validar_vacios()) {
            if (Double.parseDouble(txt_total.getText()) != 0) {
                try {
                    String num_factura = txt_num_fac.getText();
                    if (!conn.verificar_usuario("SELECT * FROM FACTURA WHERE id_factura='" + num_factura + "'")) {
                        String fecha = new SimpleDateFormat("yyyy-MM-dd").format(date_fecha.getDate());
                        double iva = dar_formato(txt_iva.getText()),
                                total_sin_iva = dar_formato(txt_sin_iva.getText()),
                                total_con_iva = dar_formato(txt_total.getText());

                        conn.insertar("INSERT INTO FACTURA (id_factura, id_cliente, id_establecimiento,tipo_factura,fecha_emision, total_sin_iva, iva, total_con_iva)"
                                + "VALUES('" + num_factura + "','" + cedula_usuario + "','" + txt_ruc_est.getText() + "','Negocio','" + fecha + "'," + total_sin_iva + "," + iva + "," + total_con_iva + ")");
                        //Registro de todos los tipos de gastos
                        registrar_gastos(num_factura);
                        borrar_campos();
                    } else {
                        JOptionPane.showMessageDialog(null, "El numero de factura ya existe en la base de datos");
                    }
                } catch (Exception e) {
                    System.err.println(e);
                }
            } else {
                JOptionPane.showMessageDialog(null, "La factura tiene un total de 0", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor, llenar todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_RegistrarFacturaActionPerformed

    private void btnEditarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEstActionPerformed
        String[] datos = new String[4];
        datos[0] = (String) combo_Establecimientos.getSelectedItem();
        datos[1] = txt_direc_est.getText();
        datos[2] = txt_telef.getText();
        datos[3] = txt_ruc_est.getText();

        new V_Establecimiento("Editar", datos, conn).setVisible(true);
    }//GEN-LAST:event_btnEditarEstActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new V_Establecimiento("Registrar", conn).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void combo_EstablecimientosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_EstablecimientosItemStateChanged
        ArrayList auxDatosEst;
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (combo_Establecimientos.getSelectedIndex() != 0) {
                auxDatosEst = conn.cambiarDatosEstablecimiento(combo_Establecimientos.getSelectedItem().toString());
                txt_ruc_est.setText(auxDatosEst.get(0).toString());
                txt_direc_est.setText(auxDatosEst.get(1).toString());
                txt_telef.setText(auxDatosEst.get(2).toString());
            } else {
                txt_ruc_est.setText("");
                txt_direc_est.setText("");
                txt_telef.setText("");
            }
        }
    }//GEN-LAST:event_combo_EstablecimientosItemStateChanged

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        restar(lbl_viaticos, txt_viaticos);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        restar(lbl_movilizacion, txt_movilizacion);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        restar(lbl_sueldos, txt_sueldos);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        restar(lbl_capacitacion, txt_capacitacion);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        restar(lbl_servbasicos, txt_servbasicos);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        restar(lbl_arriendo, txt_arriendo);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        restar(lbl_mercaderia, txt_mercaderia);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void agregar_todo() {
        JTextField campos[] = {txt_movilizacion, txt_mercaderia, txt_servbasicos, txt_arriendo, txt_viaticos, txt_capacitacion, txt_sueldos, txt_herramientas, txt_suministros};
        JLabel labels[] = {lbl_movilizacion, lbl_mercaderia, lbl_servbasicos, lbl_arriendo, lbl_viaticos, lbl_capacitacion, lbl_sueldos, lbl_herramientas, lbl_suministros};
        String valor;
        for (int i = 0; i < 9; i++) {
            valor = campos[i].getText();
            if (!valor.equals("")) {
                sumar(labels[i], campos[i]);
            }
        }
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        agregar_todo();
        double totalNoIva = Double.parseDouble(lbl_mercaderia.getText()) + Double.parseDouble(lbl_arriendo.getText())
                + Double.parseDouble(lbl_servbasicos.getText()) + Double.parseDouble(lbl_capacitacion.getText())
                + Double.parseDouble(lbl_sueldos.getText()) + Double.parseDouble(lbl_movilizacion.getText()) + Double.parseDouble(lbl_viaticos.getText())
                + Double.parseDouble(lbl_herramientas.getText()) + Double.parseDouble(lbl_suministros.getText());
        txt_sin_iva.setText(totalNoIva + "");   // TODO add your handling code here:
        double totalIVA = totalNoIva + Double.parseDouble(txt_iva.getText());
        txt_total.setText(totalIVA + "");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        sumar(lbl_viaticos, txt_viaticos);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        sumar(lbl_movilizacion, txt_movilizacion);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        sumar(lbl_servbasicos, txt_servbasicos);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        sumar(lbl_sueldos, txt_sueldos);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        sumar(lbl_capacitacion, txt_capacitacion);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        sumar(lbl_arriendo, txt_arriendo);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sumar(JLabel lbl, JTextField txt) {
        String valor = txt.getText();
        if (!valor.equals("")) {
            lbl.setText(Double.parseDouble(lbl.getText()) + Double.parseDouble(valor) + "");
            txt.setText("");
        }

    }

    private void restar(JLabel lbl, JTextField txt) {
        String valor = txt.getText();
        if (!valor.equals("")) {
            double res = Double.parseDouble(lbl.getText()) - Double.parseDouble(valor);
            if (res < 0) {
                lbl.setText("0.0");
            } else {
                lbl.setText(res + "");
            }
            txt.setText("");
        }

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        sumar(lbl_mercaderia, txt_mercaderia);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void filtrar(java.awt.event.KeyEvent evt, JTextField txt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && !(c == '.')) {
            getToolkit();
            evt.consume();
        }
        if ((c == '.') && (txt_mercaderia.getText().contains("."))) {
            getToolkit();
            evt.consume();
        }
    }

    private void txt_viaticosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_viaticosKeyTyped
        filtrar(evt, txt_viaticos);
    }//GEN-LAST:event_txt_viaticosKeyTyped

    private void txt_servbasicosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_servbasicosKeyTyped
        filtrar(evt, txt_servbasicos);
    }//GEN-LAST:event_txt_servbasicosKeyTyped

    private void txt_movilizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_movilizacionKeyTyped
        filtrar(evt, txt_movilizacion);
    }//GEN-LAST:event_txt_movilizacionKeyTyped

    private void txt_sueldosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sueldosKeyTyped
        filtrar(evt, txt_sueldos);
    }//GEN-LAST:event_txt_sueldosKeyTyped

    private void txt_capacitacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_capacitacionKeyTyped
        filtrar(evt, txt_capacitacion);
    }//GEN-LAST:event_txt_capacitacionKeyTyped

    private void txt_arriendoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_arriendoKeyTyped
        filtrar(evt, txt_arriendo);
    }//GEN-LAST:event_txt_arriendoKeyTyped

    private void txt_mercaderiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mercaderiaKeyTyped
        filtrar(evt, txt_mercaderia);
    }//GEN-LAST:event_txt_mercaderiaKeyTyped

    private void txt_ivaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ivaKeyTyped
        filtrar(evt, txt_iva);
    }//GEN-LAST:event_txt_ivaKeyTyped

    private void txt_suministrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_suministrosKeyTyped
        filtrar(evt, txt_suministros);
    }//GEN-LAST:event_txt_suministrosKeyTyped

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        sumar(lbl_suministros, txt_suministros);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        restar(lbl_suministros, txt_suministros);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void txt_herramientasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_herramientasKeyTyped
        filtrar(evt, txt_herramientas);
    }//GEN-LAST:event_txt_herramientasKeyTyped

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        sumar(lbl_herramientas, txt_herramientas);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        restar(lbl_herramientas, txt_herramientas);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void txt_num_facKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_num_facKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || txt_num_fac.getText().length()>14) {
            evt.consume();
        }
        if(txt_num_fac.getText().length()==3 ||txt_num_fac.getText().length()==7){            
            txt_num_fac.setText(txt_num_fac.getText()+"-");
        }
    }//GEN-LAST:event_txt_num_facKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturaManualNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturaManualNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturaManualNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturaManualNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                // new FacturaManualNew().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarEst;
    private javax.swing.JButton btn_RegistrarFactura;
    public static javax.swing.JComboBox<String> combo_Establecimientos;
    private com.toedter.calendar.JDateChooser date_fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_arriendo;
    private javax.swing.JLabel lbl_capacitacion;
    private javax.swing.JLabel lbl_herramientas;
    private javax.swing.JLabel lbl_mercaderia;
    private javax.swing.JLabel lbl_movilizacion;
    private javax.swing.JLabel lbl_servbasicos;
    private javax.swing.JLabel lbl_sueldos;
    private javax.swing.JLabel lbl_suministros;
    private javax.swing.JLabel lbl_viaticos;
    private javax.swing.JPanel panel_establecimiento;
    private javax.swing.JPanel panel_establecimiento1;
    private javax.swing.JTextField txt_arriendo;
    private javax.swing.JTextField txt_capacitacion;
    private javax.swing.JTextField txt_direc_est;
    private javax.swing.JTextField txt_herramientas;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_mercaderia;
    private javax.swing.JTextField txt_movilizacion;
    private javax.swing.JTextField txt_num_fac;
    private javax.swing.JTextField txt_ruc_est;
    private javax.swing.JTextField txt_servbasicos;
    private javax.swing.JTextField txt_sin_iva;
    private javax.swing.JTextField txt_sueldos;
    private javax.swing.JTextField txt_suministros;
    private javax.swing.JTextField txt_telef;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_viaticos;
    // End of variables declaration//GEN-END:variables
}
