/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Interfaces.Cliente;
import static Interfaces.Cliente.cliente;
import static Interfaces.Detalle.detalle;
import aplicacioneslibres.CargarXMLTotal;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author patriciochavez
 */
public class Producto extends javax.swing.JFrame {

    public String product[] = new String[2];

    public String[] getProduct() {
        return product;
    }

    public void setProduct(String[] product) {
        this.product = product;
    }

    /**
     * Creates new form Inicio
     */
    public Producto() {
        initComponents();
        
        CargarXMLTotal ct = new CargarXMLTotal();
        ArrayList aux = ct.cargarTodo("aldo.xml");

        for (Object el : aux) {
            cbxDesc.addItem(el.toString());
            cbxPrecio.addItem(el.toString());
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxDesc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxPrecio = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnAtrasPro = new javax.swing.JButton();
        btnGuardarPro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Descripcion");

        cbxDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDescActionPerformed(evt);
            }
        });

        jLabel2.setText("Precio Unitario");

        cbxPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPrecioActionPerformed(evt);
            }
        });

        jLabel5.setText("Producto");

        btnAtrasPro.setText("Atras");
        btnAtrasPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasProActionPerformed(evt);
            }
        });

        btnGuardarPro.setText("Guardar");
        btnGuardarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(341, Short.MAX_VALUE)
                        .addComponent(btnAtrasPro)
                        .addGap(108, 108, 108)
                        .addComponent(btnGuardarPro))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxPrecio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxDesc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtrasPro)
                    .addComponent(btnGuardarPro))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDescActionPerformed

    private void cbxPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPrecioActionPerformed

    private void btnAtrasProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasProActionPerformed
        // TODO add your handling code here:
        Factura fac = new Factura();
        fac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasProActionPerformed

    private void btnGuardarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProActionPerformed
        // TODO add your handling code here:
        StringTokenizer tk;
        String aux = "";
        
        tk = new StringTokenizer(cbxDesc.getSelectedItem().toString(), "-");
        aux = tk.nextToken();
        product[0] = aux;
        
        tk = new StringTokenizer(cbxPrecio.getSelectedItem().toString(), "-");
        aux = tk.nextToken();
        product[1] = aux;
        
        String nombreFac = "";//Inicio.nombreFac;

        File archivo = new File("src/" + nombreFac + ".txt");
        File facturas = new File("src/tipoFacturas.txt");

        try {
            FileWriter writeFac = new FileWriter(facturas);
            BufferedWriter bw = new BufferedWriter(writeFac);
            bw.write(nombreFac);
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            FileWriter escribir = new FileWriter(archivo);
            for (int i = 0; i < 4; i++) {
                escribir.write(Cliente.cliente[i] + "\n");
            }
            for (int i = 0; i < 2; i++) {
                escribir.write(Detalle.detalle[i] + "\n");
            }
            for (int i = 0; i < 6; i++) {
                escribir.write(Factura.factura[i] + "\n");
            }
            for (int i = 0; i < 2; i++) {
                escribir.write(product[i] + "\n");
            }
            escribir.close();
            
            
            //System.out.println("Ya se guardo");
        } catch (IOException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarProActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasPro;
    private javax.swing.JButton btnGuardarPro;
    private javax.swing.JComboBox<String> cbxDesc;
    private javax.swing.JComboBox<String> cbxPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
